openapi: 3.0.0
info:
  description: This is an API example
  version: "0.0.1"
  title: API-Example
tags:
  - name: hello
paths:
  '/hello':
    get:
      operationId: getHello
      tags: [hello]
      summary: Returns a greeting
      responses:
        '200':
          description: Greeting
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Greeting'
components:
  schemas:
    Greeting:
      type: object
      properties:
        message: {type: string}
